/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peluqueria_petshop.igu;

import java.awt.Color;

/**
 *
 * @author Roman
 */
public class Principal extends javax.swing.JFrame {

    private int xMouse, yMouse;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new javax.swing.JPanel();
        menuImage = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        panelClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JPanel();
        txtCargarDatos = new javax.swing.JLabel();
        btnVerDatos = new javax.swing.JPanel();
        txtVerDatos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage.setBackground(new java.awt.Color(204, 204, 255));

        menuImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Roman\\Downloads\\peluqueriacanina.jpg")); // NOI18N
        menuImage.setText("jLabel2");

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addComponent(menuImage, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, Short.MAX_VALUE)
        );

        getContentPane().add(panelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        navBar.setBackground(new java.awt.Color(255, 255, 255));
        navBar.setForeground(new java.awt.Color(60, 63, 65));
        navBar.setToolTipText("");
        navBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navBarMouseDragged(evt);
            }
        });
        navBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navBarMousePressed(evt);
            }
        });

        panelClose.setBackground(new java.awt.Color(255, 255, 255));
        panelClose.setForeground(new java.awt.Color(0, 0, 0));

        btnClose.setBackground(new java.awt.Color(255, 255, 153));
        btnClose.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 0, 0));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCloseLayout = new javax.swing.GroupLayout(panelClose);
        panelClose.setLayout(panelCloseLayout);
        panelCloseLayout.setHorizontalGroup(
            panelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        panelCloseLayout.setVerticalGroup(
            panelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCloseLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarLayout.createSequentialGroup()
                .addGap(0, 663, Short.MAX_VALUE)
                .addComponent(panelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addComponent(panelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 50));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        title.setBackground(new java.awt.Color(51, 51, 51));
        title.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(51, 51, 51));
        title.setText("PELUQUERIA CANINA");

        btnCargarDatos.setBackground(new java.awt.Color(102, 102, 102));

        txtCargarDatos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        txtCargarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCargarDatos.setText("CARGAR DATOS");
        txtCargarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCargarDatos.setPreferredSize(new java.awt.Dimension(100, 25));
        txtCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCargarDatosLayout = new javax.swing.GroupLayout(btnCargarDatos);
        btnCargarDatos.setLayout(btnCargarDatosLayout);
        btnCargarDatosLayout.setHorizontalGroup(
            btnCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btnCargarDatosLayout.setVerticalGroup(
            btnCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnVerDatos.setBackground(new java.awt.Color(102, 102, 102));

        txtVerDatos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtVerDatos.setForeground(new java.awt.Color(255, 255, 255));
        txtVerDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVerDatos.setText("VER DATOS");
        txtVerDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtVerDatos.setPreferredSize(new java.awt.Dimension(100, 25));
        txtVerDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVerDatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtVerDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtVerDatosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVerDatosLayout = new javax.swing.GroupLayout(btnVerDatos);
        btnVerDatos.setLayout(btnVerDatosLayout);
        btnVerDatosLayout.setHorizontalGroup(
            btnVerDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVerDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btnVerDatosLayout.setVerticalGroup(
            btnVerDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVerDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 460, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_navBarMousePressed

    private void navBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_navBarMouseDragged

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        panelClose.setBackground(Color.red);
        btnClose.setForeground(Color.white);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        panelClose.setBackground(Color.white);
        btnClose.setForeground(Color.black);
    }//GEN-LAST:event_btnCloseMouseExited

    private void txtCargarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseEntered
        btnCargarDatos.setBackground(new Color(70,70,70));
        txtCargarDatos.setForeground(new Color (250,250,250));
    }//GEN-LAST:event_txtCargarDatosMouseEntered

    private void txtCargarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseExited
        btnCargarDatos.setBackground(new Color(102,102,102));
        txtCargarDatos.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_txtCargarDatosMouseExited

    private void txtVerDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVerDatosMouseEntered
        btnVerDatos.setBackground(new Color(70,70,70));
        txtVerDatos.setForeground(new Color (250,250,250));
    }//GEN-LAST:event_txtVerDatosMouseEntered

    private void txtVerDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVerDatosMouseExited
        btnVerDatos.setBackground(new Color(102,102,102));
        txtVerDatos.setForeground(new Color (255,255,255));
    }//GEN-LAST:event_txtVerDatosMouseExited

    private void txtCargarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseClicked
        CargaDatos paginaCargaDatos = new CargaDatos();
        
        paginaCargaDatos.setVisible(true);
        paginaCargaDatos.setLocationRelativeTo(null);
    }//GEN-LAST:event_txtCargarDatosMouseClicked

    private void txtVerDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVerDatosMouseClicked
        VerDatos paginaVerDatos = new VerDatos();
        
        paginaVerDatos.setVisible(true);
        paginaVerDatos.setLocationRelativeTo(null);
    }//GEN-LAST:event_txtVerDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCargarDatos;
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel btnVerDatos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel menuImage;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel panelClose;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtCargarDatos;
    private javax.swing.JLabel txtVerDatos;
    // End of variables declaration//GEN-END:variables
}
